# Generated by Django 6.0.4 on 2026-05-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_type_question_resultat_tentative'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resultat',
        ),
    ]
