# Generated by Django 6.0.4 on 2026-05-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_certificat_cours_alter_certificat_etudiant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultat',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='resultat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='resultat',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultat',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
